version: "3"
services:
  app:
    container_name: app
    command: bash -c "python3.6 src/manage.py migrate && python3.6 src/manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5050:5432
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always