# Generated by Django 2.2.3 on 2019-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_link', models.CharField(max_length=255)),
                ('short_link', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
