# Generated by Django 2.2.3 on 2019-07-29 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortener',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='origin_link',
            field=models.URLField(max_length=255, unique=True, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterUniqueTogether(
            name='shortener',
            unique_together={('user', 'origin_link')},
        ),
    ]
