# Generated by Django 2.2.3 on 2019-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190729_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='origin_link',
            field=models.URLField(max_length=255, verbose_name='Оригинальная ссылка'),
        ),
    ]
